version: "3.7"
services:
  book-php:
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
    image: book
    container_name: book-php
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - book
    depends_on:
      - book-mysql
      - book-nginx

  book-mysql:
    image: mysql:8
    container_name: book-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'book'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'Author'
      MYSQL_PASSWORD: 'password'
    ports:
    - '3306:3306'
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
      - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
      - ./.docker/mysql-files:/var/lib/mysql-files
    networks:
      - book

  book-nginx:
    image: nginx
    container_name: book-nginx
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./book_admin:/var/www
      - .docker/nginx/templates:/etc/nginx/templates
    networks:
      - book

networks:
  book:
    driver: bridge
